[project]
name = "example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "matplotlib>=3.10.0",
    "requests>=2.32.3",
    "ruff>=0.9.1",
]
